---
# tasks file for python
- name: install python for ubuntu
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: install pip
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
